"use client";

export const APP_SIDEBAR_EXPANDED_WIDTH = 256;
export const APP_SIDEBAR_COLLAPSED_WIDTH = 48;

export const APP_SIDEBAR_EXPANDED_WIDTH_CSS = `${APP_SIDEBAR_EXPANDED_WIDTH}px`;
export const APP_SIDEBAR_COLLAPSED_WIDTH_CSS = `${APP_SIDEBAR_COLLAPSED_WIDTH}px`;

export const DESKTOP_DOCKED_PANEL_DEFAULT_WIDTH = 256;
export const DESKTOP_DOCKED_PANEL_MIN_WIDTH = 256;
export const DESKTOP_DOCKED_PANEL_MAX_WIDTH = 560;

export const MOBILE_DOCKED_PANEL_DEFAULT_WIDTH = 280;
export const MOBILE_DOCKED_PANEL_MIN_WIDTH = MOBILE_DOCKED_PANEL_DEFAULT_WIDTH;
export const MOBILE_DOCKED_PANEL_DEFAULT_WIDTH_CSS = `${MOBILE_DOCKED_PANEL_DEFAULT_WIDTH}px`;
