import { openai } from "@ai-sdk/openai";
import { generateText } from "ai";
import { v } from "convex/values";
import { BASE_CHAT_SYSTEM_PROMPT } from "../packages/ai/src/prompts.mjs";
import { internal } from "./_generated/api";
import { internalAction } from "./_generated/server";

const MAX_AUTOMATION_HISTORY_MESSAGES = 40;

const automationRunReasonValidator = v.union(
	v.literal("scheduled"),
	v.literal("manual"),
);

const createMessageId = () =>
	`msg-${Date.now()}-${Math.random().toString(36).slice(2, 10)}`;

const createTextMessage = ({
	id,
	role,
	text,
	metadata,
}: {
	id: string;
	role: "user" | "assistant";
	text: string;
	metadata: Record<string, unknown>;
}) => ({
	id,
	role,
	partsJson: JSON.stringify([{ type: "text", text }]),
	metadataJson: JSON.stringify(metadata),
	text,
	createdAt: Date.now(),
});

const buildAutomationSystemPrompt = ({
	targetLabel,
	appSources,
	notes,
}: {
	targetLabel: string;
	appSources: Array<{ label: string }>;
	notes: Array<{ title: string; text: string; updatedAt: number }>;
}) => {
	const noteContext = notes
		.map((note) =>
			[
				`Title: ${note.title}`,
				`Updated: ${new Date(note.updatedAt).toISOString()}`,
				note.text,
			].join("\n"),
		)
		.join("\n\n---\n\n");

	return [
		BASE_CHAT_SYSTEM_PROMPT,
		"This response is being generated by a scheduled automation.",
		`Automation target project: ${targetLabel}.`,
		appSources.length > 0
			? `Selected app sources: ${appSources.map((source) => source.label).join(", ")}.`
			: "",
		"Use the automation prompt as the task. If project notes are provided, use them as context and do not invent missing facts.",
		noteContext ? `Recent project notes:\n\n${noteContext}` : "",
	]
		.filter(Boolean)
		.join("\n\n");
};

export const runAutomation = internalAction({
	args: {
		automationId: v.id("automations"),
		scheduledFor: v.number(),
		reason: automationRunReasonValidator,
	},
	returns: v.null(),
	handler: async (ctx, args) => {
		if (!process.env.OPENAI_API_KEY) {
			throw new Error("OPENAI_API_KEY is not configured in Convex.");
		}

		const run = await ctx.runMutation(internal.automations.beginRun, args);
		if (run.status === "skipped") {
			return null;
		}

		const userMessageId = createMessageId();
		const assistantMessageId = createMessageId();
		const metadata = {
			source: "automation",
			automationId: String(run.automationId),
			automationRunId: String(run.runId),
			scheduledFor: run.scheduledFor,
			reason: run.reason,
		};

		try {
			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: run.prompt,
				model: run.model,
				forceTitle: true,
				message: createTextMessage({
					id: userMessageId,
					role: "user",
					text: run.prompt,
					metadata,
				}),
			});

			const history = await ctx.runQuery(internal.chats.getMessagesForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				chatId: run.chatId,
			});
			const messages = history
				.slice(-MAX_AUTOMATION_HISTORY_MESSAGES)
				.filter(
					(message) =>
						(message.role === "user" || message.role === "assistant") &&
						message.text.trim(),
				)
				.map((message) => ({
					role: message.role,
					content: message.text,
				}));
			const result = await generateText({
				model: openai(run.model),
				system: buildAutomationSystemPrompt({
					targetLabel: run.targetLabel,
					appSources: run.appSources,
					notes: run.notes,
				}),
				messages,
			});

			await ctx.runMutation(internal.chats.saveMessageForOwner, {
				ownerTokenIdentifier: run.ownerTokenIdentifier,
				workspaceId: run.workspaceId,
				authorName: run.authorName,
				chatId: run.chatId,
				title: run.title,
				preview: result.text,
				model: run.model,
				forceTitle: true,
				message: createTextMessage({
					id: assistantMessageId,
					role: "assistant",
					text: result.text,
					metadata,
				}),
			});

			await ctx.runMutation(internal.automations.completeRun, {
				automationId: run.automationId,
				runId: run.runId,
				userMessageId,
				assistantMessageId,
			});
		} catch (error) {
			await ctx.runMutation(internal.automations.failRun, {
				automationId: run.automationId,
				runId: run.runId,
				error: error instanceof Error ? error.message : String(error),
			});
			throw error;
		}

		return null;
	},
});
