"use client";

export const DESKTOP_DOCKED_PANEL_DEFAULT_WIDTH = 256;
export const DESKTOP_DOCKED_PANEL_MIN_WIDTH = 256;
export const DESKTOP_DOCKED_PANEL_MAX_WIDTH = 560;
export const MOBILE_DOCKED_PANEL_MIN_WIDTH = 280;
